### ISSUE TITLE
TypeError: Request path contains unescaped characters

### ISSUE THREAD

**Issue by fan-ipads-sjtu** [fan-ipads-sjtu/SE26017-yf-hfq-lhy-frontend#2]
An error is reported if the new post contains a space or Chinese characters.

The error report is:
```
TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:137:13)
    at Object.request (http.js:39:10)
    at /usr/src/app/server.js:136:24
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at /usr/src/app/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/usr/src/app/node_modules/raw-body/index.js:224:16)
    at done (/usr/src/app/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/usr/src/app/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:111:20)
```

**Comment by Lei-Houjyu** [comment]
Fixed. See commit 1d93fa9764913677a8e48dea9f9a681e87cad730.
